version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: yapper
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    environment:
      JWT_SECRET_KEY: ${JWT_SECRET}
      DATABASE_URL: postgresql://postgres:${DATABASE_PASSWORD}@postgres:5432/yapper
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
